version: '3.9'

services:
 minio-server:
  image: minio/minio
  restart: always
  volumes:
   - ./minio:/data
  ports:
   - "9000:9000"
   - "46203:46203"
  environment:
   MINIO_ACCESS_KEY: 123123123
   MINIO_SECRET_KEY: 123123123
  command: server /data --console-address :46203